name: push_swap

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2 # Checkout the repository content to github runner.
      with:
        submodules: recursive

    - name: Welcome message
      run: echo Welcome to push-swap!
    
    - name: build
      run: make all

    - name: run acceptance test
      run: ./test/main/acceptance_test.sh

    - name: run unit-tests
      run: make test_run 
